"""Known SDRF column headers exposed by the metadata editor.

This is a local snapshot of the unique column names in the official BigBio
``sdrf-templates`` registry (retrieved 2026-08-27). Keeping the names local
makes the picker complete and usable without network access.
"""

from __future__ import annotations


KNOWN_SDRF_HEADERS = tuple(filter(None, r"""
assay name
characteristics[age]
characteristics[alkalinity method]
characteristics[alkalinity]
characteristics[alkyl diethers]
characteristics[altitude]
characteristics[aluminum saturation method]
characteristics[aluminum saturation]
characteristics[aminopeptidase activity]
characteristics[ammonium]
characteristics[analyte class]
characteristics[ancestry category]
characteristics[ann arbor stage]
characteristics[antibiotic treatment]
characteristics[antibody enrichment]
characteristics[atmospheric data]
characteristics[bacterial carbon production]
characteristics[bacterial respiration]
characteristics[biological replicate]
characteristics[biomass estimation]
characteristics[biomass]
characteristics[biopsy site]
characteristics[biorepository]
characteristics[biosample accession number]
characteristics[bishomohopanol]
characteristics[body mass index]
characteristics[broad-scale environmental context]
characteristics[bromide]
characteristics[calcium]
characteristics[carbon nitrogen ratio]
characteristics[cell cycle phase]
characteristics[cell diameter]
characteristics[cell identifier]
characteristics[cell line authentication]
characteristics[cell line]
characteristics[cell type]
characteristics[cell viability]
characteristics[cellosaurus accession]
characteristics[cellosaurus name]
characteristics[cells per well]
characteristics[chemical administration]
characteristics[chloride]
characteristics[chlorophyll]
characteristics[clinical data]
characteristics[clinical history]
characteristics[collection date]
characteristics[compound]
characteristics[conductivity]
characteristics[crop rotation]
characteristics[crosslink distance]
characteristics[crosslinking reaction time]
characteristics[crosslinking temperature]
characteristics[culture medium]
characteristics[current land use]
characteristics[current vegetation]
characteristics[density]
characteristics[depletion]
characteristics[depth]
characteristics[developmental stage]
characteristics[diether lipids]
characteristics[disease staging]
characteristics[disease]
characteristics[dissolved carbon dioxide]
characteristics[dissolved hydrogen]
characteristics[dissolved inorganic carbon]
characteristics[dissolved inorganic nitrogen]
characteristics[dissolved inorganic phosphorus]
characteristics[dissolved organic carbon]
characteristics[dissolved organic nitrogen]
characteristics[dissolved oxygen]
characteristics[dose]
characteristics[downward PAR]
characteristics[drainage classification]
characteristics[dukes stage]
characteristics[elevation]
characteristics[enrichment marker]
characteristics[enrichment process]
characteristics[environmental medium]
characteristics[ethnicity]
characteristics[exposure duration]
characteristics[extreme unusual properties of heavy metals method]
characteristics[extreme unusual properties of heavy metals]
characteristics[fluorescence]
characteristics[forward scatter]
characteristics[gastrointestinal tract disorder]
characteristics[genetic modification]
characteristics[genotype]
characteristics[geographic location]
characteristics[gleason score]
characteristics[glucosidase activity]
characteristics[growth condition]
characteristics[height]
characteristics[histologic subtype]
characteristics[history of agrochemical additions]
characteristics[history of extreme event]
characteristics[history of fire]
characteristics[history of flooding]
characteristics[history of previous land use]
characteristics[history of tillage]
characteristics[host age]
characteristics[host body product]
characteristics[host body site]
characteristics[host body temperature]
characteristics[host body-mass index]
characteristics[host contamination]
characteristics[host diet]
characteristics[host disease status]
characteristics[host family relationship]
characteristics[host genotype]
characteristics[host height]
characteristics[host last meal]
characteristics[host occupation]
characteristics[host organism]
characteristics[host phenotype]
characteristics[host pulse]
characteristics[host sex]
characteristics[host subject id]
characteristics[host total mass]
characteristics[ihmc medication code]
characteristics[immunopeptidome enrichment method]
characteristics[individual]
characteristics[last follow up]
characteristics[light intensity]
characteristics[link classification information]
characteristics[link climate information]
characteristics[liver disorder]
characteristics[local environmental context]
characteristics[magnesium]
characteristics[material type]
characteristics[mean annual precipitation]
characteristics[mean annual temperature]
characteristics[mean friction velocity]
characteristics[mean peak friction velocity]
characteristics[mean seasonal precipitation]
characteristics[mean seasonal temperature]
characteristics[medical history performed]
characteristics[menopausal status]
characteristics[metastasis site]
characteristics[mhc protein complex]
characteristics[mhc typing method]
characteristics[mhc typing]
characteristics[microbiome source]
characteristics[mitotic rate]
characteristics[mock community composition]
characteristics[mock community]
characteristics[n-alkanes]
characteristics[nitrate]
characteristics[nitrite]
characteristics[nitrogen]
characteristics[observed host symbionts]
characteristics[organic carbon]
characteristics[organic matter]
characteristics[organic nitrogen]
characteristics[organism part]
characteristics[organism]
characteristics[pH method]
characteristics[particulate organic carbon]
characteristics[particulate organic nitrogen]
characteristics[passage number]
characteristics[perturbation]
characteristics[petroleum hydrocarbon]
characteristics[ph]
characteristics[phaeopigments]
characteristics[phenotype]
characteristics[phosphate]
characteristics[phospholipid fatty acid]
characteristics[photon flux]
characteristics[pooled sample]
characteristics[pooling of DNA extracts]
characteristics[potassium]
characteristics[pre-existing condition]
characteristics[pressure]
characteristics[primary production]
characteristics[profile position]
characteristics[project name]
characteristics[redox potential]
characteristics[salinity]
characteristics[sample collection method]
characteristics[sample matrix]
characteristics[sample name]
characteristics[sample storage temperature]
characteristics[sample storage]
characteristics[sample type]
characteristics[sampling depth zone]
characteristics[sampling site]
characteristics[sampling time]
characteristics[sex]
characteristics[side scatter]
characteristics[sieving]
characteristics[silicate]
characteristics[single cell isolation protocol]
characteristics[slope aspect]
characteristics[slope gradient]
characteristics[smoking status]
characteristics[sodium]
characteristics[soil horizon]
characteristics[soil local classification method]
characteristics[soil taxonomic local classification]
characteristics[soil taxonomic of FAO classification]
characteristics[soil texture method]
characteristics[soil texture]
characteristics[soil type method]
characteristics[soil type]
characteristics[soil water content method]
characteristics[soluble reactive phosphorus]
characteristics[spatial coordinates]
characteristics[special diet]
characteristics[spiked compound]
characteristics[strain or breed]
characteristics[sulfate]
characteristics[sulfide]
characteristics[survival time]
characteristics[suspended particulate matter]
characteristics[synthetic peptide]
characteristics[temperature]
characteristics[tidal stage]
characteristics[tissue mass]
characteristics[tissue supergroup]
characteristics[total depth of water volume]
characteristics[total dissolved nitrogen]
characteristics[total inorganic nitrogen]
characteristics[total nitrogen concentration]
characteristics[total nitrogen content method]
characteristics[total nitrogen content]
characteristics[total organic carbon method]
characteristics[total organic carbon]
characteristics[total particulate carbon]
characteristics[total phosphorus]
characteristics[treatment response]
characteristics[treatment status]
characteristics[treatment]
characteristics[tumor grading]
characteristics[tumor mass]
characteristics[tumor size]
characteristics[tumor stage]
characteristics[turbidity]
characteristics[water content]
characteristics[water current]
characteristics[weight]
characteristics[weiss grade]
comment[acquisition date]
comment[acquisition method]
comment[alkylation reagent]
comment[bacterial production]
comment[carrier channel]
comment[carrier gas]
comment[chemical cross-linking coupled with ms]
comment[chromatography column]
comment[chromatography type]
comment[cleavage agent details]
comment[collision energy]
comment[contaminant database]
comment[cross-linker]
comment[crosslink enrichment method]
comment[crosslinker concentration]
comment[crosslinker to protein ratio]
comment[current vegetation method]
comment[data file]
comment[derivatization agent]
comment[derivatization]
comment[dilution]
comment[dissociation method]
comment[elution conditions]
comment[expected organism list]
comment[extraction method]
comment[extraction solvent]
comment[facs nozzle size]
comment[facs sorting mode]
comment[flow rate]
comment[fraction identifier]
comment[fractionation method]
comment[fragment mass tolerance]
comment[gc column]
comment[gradient]
comment[history of previous land use method]
comment[horizon method]
comment[instrument]
comment[internal standard]
comment[ion source]
comment[isolation window width]
comment[label]
comment[lc batch]
comment[lcm microscope model]
comment[link to additional analysis]
comment[lot number]
comment[metabolite assignment file md5]
comment[metabolite assignment file]
comment[metagenome accession]
comment[microbial biomass method]
comment[microbial biomass]
comment[microfluidics chip type]
comment[miscellaneous parameter]
comment[mobile phase a]
comment[mobile phase b]
comment[modification parameters]
comment[ms max charge]
comment[ms max im]
comment[ms max mz]
comment[ms max rt]
comment[ms min charge]
comment[ms min im]
comment[ms min mz]
comment[ms min rt]
comment[ms1 scan range]
comment[ms2 mass analyzer]
comment[ms2 max mz]
comment[ms2 min mz]
comment[ms2 scan range]
comment[ms3 max mz]
comment[ms3 min mz]
comment[ms3 scan range]
comment[nanopots chip version]
comment[normalization method]
comment[organism count]
comment[oven program]
comment[oxygenation status of sample]
comment[panel name]
comment[plate]
comment[platform]
comment[precursor mass tolerance]
comment[processed data file md5]
comment[processed data file]
comment[proteomics data acquisition method]
comment[quantification unit]
comment[quenching reagent]
comment[raw data file md5]
comment[reduction reagent]
comment[reference channel]
comment[sample preparation batch]
comment[sample storage duration]
comment[sample storage location]
comment[sample storage temperature]
comment[sample volume or weight for DNA extraction]
comment[scan polarity]
comment[scan window lower limit]
comment[scan window upper limit]
comment[sdrf annotation tool]
comment[sdrf template]
comment[sdrf validation hash]
comment[sdrf version]
comment[size-fraction lower threshold]
comment[size-fraction upper threshold]
comment[storage conditions]
comment[technical replicate]
comment[tissue section]
source name
technology type
""".splitlines()))


def column_group(header: str) -> str:
    if header.startswith("characteristics["):
        return "Characteristics"
    if header.startswith("comment["):
        return "Comments"
    if header.startswith("factor value["):
        return "Experimental factors"
    return "Core SDRF"

